---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: anomaly-detection
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: anomaly-detection
    apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  #image: index.docker.io/oawofolu/image-processor-default@sha256:ba3df083e2abf17117488d918ba2321ec7ba9999981077416725cb3f34b09c6e
  params:
    - name: clusterBuilder
      value: full
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/openapi.json"
        system: anomaly-detection
        owner: team-anomaly-detection
        description: "A set of API endpoints for the ML Anomaly Detection Demo App."
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.${DATA_E2E_BASE_URL}
    - name: STREAMLIT_SERVER_ENABLE_STATIC_SERVING
      value: true
  source:
    git:
      url: https://github.com/agapebondservant/demo-ml-base.git
      ref:
        branch: main